server:
  port: 8081

spring:
  application:
    name: comment-producer
  data:
    mongodb:
      uri: "mongodb://localhost:27017/comments"

aws:
  security:
    accessKeyId: ${AWS_ACCESS_KEY_ID:local}
    secretAccessKey: ${AWS_SECRET_ACCESS_KEY:local}
  queue:
    url:
      car: ${AWS_SQS_QUEUE_URL:https://localhost.localstack.cloud:4566/000000000000/sqs-rent-queue}