spring:
  datasource:
    url: jdbc:postgresql://postgres_sb_img:5432/project_auto
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    show-sql: false

  flyway:
    enabled: true

api:
  security:
    token:
      secret: BE1B44F8953BB2978C54FAA622EA1